puts "The students of Hillhoop Academy"
puts "-----------------"
puts "Ms. Fanny Craddock"
puts "Mr. Sam Akindele"
puts "Ms. Aisa Bello"
puts "Mr. Juliana Ogunmola"
puts "Miss. Sabrina Ogunmola"
puts "Mr. John van der Merwe"
puts "Mr. Jushua Funke"
puts "Aimen Subhi"
